language: node_js
node_js:   - "6"
install:
  - npm install
script:
  - bash ./travis/gh-pages.sh
env:
  global:
  - ENCRYPTION_LABEL: ""
  - COMMIT_AUTHOR_EMAIL: "matthiasmeeierkoch@hotmail.com"
  - DEPLOY_DIR: "./docs/bocado/dist"
  - SOURCE_BRANCH: "master"
  - TARGET_BRANCH: "gh-pages"
branches:
  only:
  - master